name: PR test workflow

on:
  pull_request_target:
    branches: [ "main" ]

jobs:
  run-pr-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout attacker PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run attacker code
        run: |
          echo "Running attacker code"
          ls -la
          env
